package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Fingerprint struct {
	Function       string   `json:"function"`
	Binary         string   `json:"binary"`
	Address        string   `json:"address"`
	Image          string   `json:"image"`
	Instructions   int      `json:"instructions"`
	MMIOReads      int      `json:"mmio_reads"`
	MMIOWrites     int      `json:"mmio_writes"`
	UniqueMMIOAddrs []string `json:"unique_mmio_addrs"`
	MMIOSequence   []string `json:"mmio_sequence"`
	Termination    string   `json:"termination"`
	Faults         int      `json:"faults"`
}

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: behaviorsynth <fingerprints.jsonl> <out_dir>\n")
		fmt.Fprintf(os.Stderr, "Generates behavioral fingerprint C bodies from Unicorn MMIO traces.\n")
		os.Exit(1)
	}

	inPath := os.Args[1]
	outDir := os.Args[2]

	os.MkdirAll(outDir, 0755)

	f, err := os.Open(inPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error opening %s: %v\n", inPath, err)
		os.Exit(1)
	}
	defer f.Close()

	var fps []Fingerprint
	dec := json.NewDecoder(f)
	for dec.More() {
		var fp Fingerprint
		if err := dec.Decode(&fp); err != nil {
			fmt.Fprintf(os.Stderr, "warning: skipping entry: %v\n", err)
			continue
		}
		fps = append(fps, fp)
	}

	if len(fps) == 0 {
		fmt.Fprintf(os.Stderr, "no fingerprints found in %s\n", inPath)
		os.Exit(1)
	}

	// Emit a global header macros file.
	macroLines := []string{
		"/* Auto-generated by behaviorsynth: MMIO extraction macros */",
		"#ifndef BEHAVIORSYNTH_MMIO_MACROS_H",
		"#define BEHAVIORSYNTH_MMIO_MACROS_H",
		"",
		"#include <stdint.h>",
		"",
		"static inline void mmio_touch32(uint32_t addr) {",
		"    volatile uint32_t *p = (volatile uint32_t *)(uintptr_t)addr;",
		"    (void)*p;",
		"}",
		"",
		"static inline uint32_t mmio_read32(uint32_t addr) {",
		"    return *((volatile uint32_t *)(uintptr_t)addr);",
		"}",
		"",
		"static inline void mmio_write32(uint32_t addr, uint32_t val) {",
		"    *((volatile uint32_t *)(uintptr_t)addr) = val;",
		"}",
		"",
		"#endif /* BEHAVIORSYNTH_MMIO_MACROS_H */",
	}
	macroPath := filepath.Join(outDir, "behaviorsynth_mmio.h")
	os.WriteFile(macroPath, []byte(strings.Join(macroLines, "\n")+"\n"), 0644)
	fmt.Fprintf(os.Stderr, "wrote %s\n", macroPath)

	generated := 0
	noMMIO := 0
	for _, fp := range fps {
		if len(fp.MMIOSequence) == 0 {
			noMMIO++
			continue
		}

		// Build the body.
		funcName := sanitizeName(fp.Function)
		imageTag := strings.ReplaceAll(filepath.Base(fp.Image), ".", "_")

		var body strings.Builder
		body.WriteString("/* task=behavioral_")
		body.WriteString(funcName)
		body.WriteString(" class=behavioral priority=critical score=25.000 */\n")
		body.WriteString("/* image=")
		body.WriteString(imageTag)
		body.WriteString(" addr=")
		body.WriteString(fp.Address)
		body.WriteString(" */\n\n")
		body.WriteString("void ")
		body.WriteString(funcName)
		body.WriteString("(void) {\n")
		body.WriteString("  /* reconstructed_micro_flow: yes */\n")

		// Deduplicate adjacent same-direction accesses.
		var deduped []string
		for _, a := range fp.MMIOSequence {
			if len(deduped) == 0 || deduped[len(deduped)-1] != a {
				deduped = append(deduped, a)
			}
		}

		// Emit inline volatile reads/writes (no helper function needed).
		for _, entry := range deduped {
			// Format: R:0xaddr or W:0xaddr:0xvalue
			parts := strings.SplitN(entry, ":", 3)
			if len(parts) < 2 {
				continue
			}
			addr := strings.TrimSpace(parts[1])
			switch parts[0] {
			case "R":
				body.WriteString(fmt.Sprintf("    (void)*((volatile uint32_t *)(uintptr_t)%sU);\n", addr))
			case "W":
				val := "0x0"
				if len(parts) == 3 {
					val = strings.TrimSpace(parts[2])
				}
				body.WriteString(fmt.Sprintf("    *((volatile uint32_t *)(uintptr_t)%sU) = %sU;\n", addr, val))
			}
		}

		body.WriteString("}\n")

		// Write the synth file (include image tag to avoid cross-image name collisions).
		imgTag := strings.ReplaceAll(strings.ReplaceAll(filepath.Base(fp.Image), ".", "_"), "-", "_")
		synthName := fmt.Sprintf("behavioral_%s__%s.synth.c", funcName, imgTag)
		outPath := filepath.Join(outDir, synthName)
		if err := os.WriteFile(outPath, []byte(body.String()), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
			continue
		}
		generated++
		fmt.Fprintf(os.Stderr, "wrote %s (%d mmio accesses in sequence)\n", outPath, len(fp.MMIOSequence))
	}

	fmt.Fprintf(os.Stderr, "\nsummary: %d generated, %d empty (no mmio), %d total fingerprints\n", generated, noMMIO, len(fps))
}

func sanitizeName(name string) string {
	name = strings.TrimSpace(name)
	// Replace non-alphanumeric chars.
	var b strings.Builder
	for _, ch := range name {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') || ch == '_' {
			b.WriteRune(ch)
		} else {
			b.WriteRune('_')
		}
	}
	s := b.String()
	if s == "" {
		s = "unknown"
	}
	// Don't start with a digit.
	if s[0] >= '0' && s[0] <= '9' {
		s = "fn_" + s
	}
	return s
}


