/* v18: faithful inline-asm */ /* 25 functions */
#include <stdint.h>
__attribute__((naked, used, section(".text.v18")))
void log_pool_init_b(void) {
    __asm__ volatile(
        ".byte 0x2d\n"
        ".byte 0xe9\n"
        ".byte 0xf0\n"
        ".byte 0x41\n"
        ".byte 0xdf\n"
        ".byte 0xf8\n"
        ".byte 0x4c\n"
        ".byte 0x80\n"
        ".byte 0x0f\n"
        ".byte 0x48\n"
        ".byte 0x1d\n"
        ".byte 0xf0\n"
        ".byte 0x53\n"
        ".byte 0xf8\n"
        ".byte 0xd8\n"
        ".byte 0xf8\n"
        ".byte 0x00\n"
        ".byte 0x30\n"
        ".byte 0xdb\n"
        ".byte 0x88\n"
        ".byte 0xb3\n"
        ".byte 0xb1\n"
        ".byte 0x0d\n"
        ".byte 0x4d\n"
        ".byte 0x0d\n"
        ".byte 0x4f\n"
        ".byte 0x0b\n"
        ".byte 0x4e\n"
        ".byte 0x00\n"
        ".byte 0x24\n"
        ".byte 0x40\n"
        ".byte 0xf2\n"
        ".byte 0x3c\n"
        ".byte 0x61\n"
        ".byte 0x38\n"
        ".byte 0x46\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xba\n"
        ".byte 0xfc\n"
        ".byte 0x01\n"
        ".byte 0x46\n"
        ".byte 0x30\n"
        ".byte 0x46\n"
        ".byte 0x1d\n"
        ".byte 0xf0\n"
        ".byte 0x46\n"
        ".byte 0xf8\n"
        ".byte 0xd8\n"
        ".byte 0xf8\n"
        ".byte 0x00\n"
        ".byte 0x20\n"
        ".byte 0x2b\n"
        ".byte 0x68\n"
        ".byte 0xd1\n"
        ".byte 0x88\n"
        ".byte 0x01\n"
        ".byte 0x34\n"
        ".byte 0xa2\n"
        ".byte 0xb2\n"
        ".byte 0x01\n"
        ".byte 0x33\n"
        ".byte 0x91\n"
        ".byte 0x42\n"
        ".byte 0x2b\n"
        ".byte 0x60\n"
        ".byte 0xec\n"
        ".byte 0xd8\n"
        ".byte 0xbd\n"
        ".byte 0xe8\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void hw_event_flag(void) {
    __asm__ volatile(
        ".byte 0x16\n"
        ".byte 0x4b\n"
        ".byte 0x70\n"
        ".byte 0xb5\n"
        ".byte 0x16\n"
        ".byte 0x4e\n"
        ".byte 0x1a\n"
        ".byte 0x68\n"
        ".byte 0x75\n"
        ".byte 0x79\n"
        ".byte 0x96\n"
        ".byte 0xf9\n"
        ".byte 0x07\n"
        ".byte 0x40\n"
        ".byte 0x02\n"
        ".byte 0xf0\n"
        ".byte 0x03\n"
        ".byte 0x02\n"
        ".byte 0x15\n"
        ".byte 0x44\n"
        ".byte 0x6d\n"
        ".byte 0xb2\n"
        ".byte 0x6f\n"
        ".byte 0xf0\n"
        ".byte 0x3d\n"
        ".byte 0x03\n"
        ".byte 0x64\n"
        ".byte 0x1b\n"
        ".byte 0x9c\n"
        ".byte 0x42\n"
        ".byte 0xb8\n"
        ".byte 0xbf\n"
        ".byte 0x1c\n"
        ".byte 0x46\n"
        ".byte 0x64\n"
        ".byte 0xb2\n"
        ".byte 0x20\n"
        ".byte 0x46\n"
        ".byte 0xf3\n"
        ".byte 0xf7\n"
        ".byte 0x27\n"
        ".byte 0xfd\n"
        ".byte 0x21\n"
        ".byte 0x46\n"
        ".byte 0x0d\n"
        ".byte 0x48\n"
        ".byte 0xf4\n"
        ".byte 0x71\n"
        ".byte 0x2a\n"
        ".byte 0x46\n"
        ".byte 0x1f\n"
        ".byte 0xf0\n"
        ".byte 0x5d\n"
        ".byte 0xfc\n"
        ".byte 0x3d\n"
        ".byte 0x34\n"
        ".byte 0x02\n"
        ".byte 0xda\n"
        ".byte 0x00\n"
        ".byte 0x23\n"
        ".byte 0xf3\n"
        ".byte 0x72\n"
        ".byte 0x70\n"
        ".byte 0xbd\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void log_alloc(void) {
    __asm__ volatile(
        ".byte 0x38\n"
        ".byte 0xb5\n"
        ".byte 0x0f\n"
        ".byte 0x4b\n"
        ".byte 0x1b\n"
        ".byte 0x68\n"
        ".byte 0x1b\n"
        ".byte 0x78\n"
        ".byte 0x01\n"
        ".byte 0x2b\n"
        ".byte 0x05\n"
        ".byte 0x46\n"
        ".byte 0x0d\n"
        ".byte 0xd0\n"
        ".byte 0x0d\n"
        ".byte 0x48\n"
        ".byte 0x7c\n"
        ".byte 0x21\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xab\n"
        ".byte 0xfd\n"
        ".byte 0x04\n"
        ".byte 0x46\n"
        ".byte 0x2c\n"
        ".byte 0xb1\n"
        ".byte 0x20\n"
        ".byte 0x46\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xac\n"
        ".byte 0xff\n"
        ".byte 0x38\n"
        ".byte 0xb1\n"
        ".byte 0x04\n"
        ".byte 0xf8\n"
        ".byte 0x01\n"
        ".byte 0x5c\n"
        ".byte 0x20\n"
        ".byte 0x46\n"
        ".byte 0x38\n"
        ".byte 0xbd\n"
        ".byte 0x00\n"
        ".byte 0xf0\n"
        ".byte 0x4b\n"
        ".byte 0xfa\n"
        ".byte 0x04\n"
        ".byte 0x46\n"
        ".byte 0xf2\n"
        ".byte 0xe7\n"
        ".byte 0x21\n"
        ".byte 0x46\n"
        ".byte 0x04\n"
        ".byte 0x48\n"
        ".byte 0xfd\n"
        ".byte 0xf7\n"
        ".byte 0x17\n"
        ".byte 0xfe\n"
        ".byte 0x20\n"
        ".byte 0x46\n"
        ".byte 0x38\n"
        ".byte 0xbd\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void timer_set_relative(void) {
    __asm__ volatile(
        ".byte 0x40\n"
        ".byte 0x01\n"
        ".byte 0x00\n"
        ".byte 0xf1\n"
        ".byte 0x80\n"
        ".byte 0x40\n"
        ".byte 0x00\n"
        ".byte 0xf5\n"
        ".byte 0x00\n"
        ".byte 0x10\n"
        ".byte 0xd0\n"
        ".byte 0xf8\n"
        ".byte 0x00\n"
        ".byte 0x3b\n"
        ".byte 0x00\n"
        ".byte 0x2b\n"
        ".byte 0x05\n"
        ".byte 0xda\n"
        ".byte 0x23\n"
        ".byte 0xf0\n"
        ".byte 0x04\n"
        ".byte 0x43\n"
        ".byte 0x43\n"
        ".byte 0xf0\n"
        ".byte 0x80\n"
        ".byte 0x63\n"
        ".byte 0xc0\n"
        ".byte 0xf8\n"
        ".byte 0x00\n"
        ".byte 0x3b\n"
        ".byte 0x70\n"
        ".byte 0x47\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void log_queue_push2(void) {
    __asm__ volatile(
        ".byte 0x2d\n"
        ".byte 0xe9\n"
        ".byte 0xf0\n"
        ".byte 0x47\n"
        ".byte 0x80\n"
        ".byte 0x46\n"
        ".byte 0x0e\n"
        ".byte 0x46\n"
        ".byte 0x17\n"
        ".byte 0x46\n"
        ".byte 0xef\n"
        ".byte 0xf3\n"
        ".byte 0x10\n"
        ".byte 0x83\n"
        ".byte 0xda\n"
        ".byte 0x07\n"
        ".byte 0x03\n"
        ".byte 0xd4\n"
        ".byte 0x72\n"
        ".byte 0xb6\n"
        ".byte 0x36\n"
        ".byte 0x4b\n"
        ".byte 0x01\n"
        ".byte 0x22\n"
        ".byte 0x1a\n"
        ".byte 0x60\n"
        ".byte 0xdf\n"
        ".byte 0xf8\n"
        ".byte 0x00\n"
        ".byte 0x91\n"
        ".byte 0x35\n"
        ".byte 0x4b\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void debug_if_check_40320038(void) {
    __asm__ volatile(
        ".byte 0x04\n"
        ".byte 0x4b\n"
        ".byte 0x1b\n"
        ".byte 0x68\n"
        ".byte 0x1b\n"
        ".byte 0x07\n"
        ".byte 0x00\n"
        ".byte 0xd1\n"
        ".byte 0x70\n"
        ".byte 0x47\n"
        ".byte 0x03\n"
        ".byte 0x49\n"
        ".byte 0x03\n"
        ".byte 0x48\n"
        ".byte 0x2d\n"
        ".byte 0xf0\n"
        ".byte 0x09\n"
        ".byte 0xb8\n"
        ".byte 0x00\n"
        ".byte 0xbf\n"
        ".byte 0x38\n"
        ".byte 0x00\n"
        ".byte 0x32\n"
        ".byte 0x40\n"
        ".byte 0x24\n"
        ".byte 0x42\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
        ".byte 0x74\n"
        ".byte 0x40\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void log_pool_init_queue(void) {
    __asm__ volatile(
        ".byte 0xf8\n"
        ".byte 0xb5\n"
        ".byte 0x0c\n"
        ".byte 0x4d\n"
        ".byte 0x0c\n"
        ".byte 0x48\n"
        ".byte 0x1d\n"
        ".byte 0xf0\n"
        ".byte 0x29\n"
        ".byte 0xf8\n"
        ".byte 0x2b\n"
        ".byte 0x68\n"
        ".byte 0x5b\n"
        ".byte 0x88\n"
        ".byte 0x83\n"
        ".byte 0xb1\n"
        ".byte 0x0a\n"
        ".byte 0x4f\n"
        ".byte 0x09\n"
        ".byte 0x4e\n"
        ".byte 0x00\n"
        ".byte 0x24\n"
        ".byte 0x0c\n"
        ".byte 0x21\n"
        ".byte 0x38\n"
        ".byte 0x46\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0x93\n"
        ".byte 0xfc\n"
        ".byte 0x01\n"
        ".byte 0x46\n"
        ".byte 0x30\n"
        ".byte 0x46\n"
        ".byte 0x1d\n"
        ".byte 0xf0\n"
        ".byte 0x1f\n"
        ".byte 0xf8\n"
        ".byte 0x2b\n"
        ".byte 0x68\n"
        ".byte 0x01\n"
        ".byte 0x34\n"
        ".byte 0x5a\n"
        ".byte 0x88\n"
        ".byte 0xa3\n"
        ".byte 0xb2\n"
        ".byte 0x9a\n"
        ".byte 0x42\n"
        ".byte 0xf1\n"
        ".byte 0xd8\n"
        ".byte 0xf8\n"
        ".byte 0xbd\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void uart_puts(void) {
    __asm__ volatile(
        ".byte 0x01\n"
        ".byte 0x78\n"
        ".byte 0x69\n"
        ".byte 0xb1\n"
        ".byte 0x10\n"
        ".byte 0xb4\n"
        ".byte 0x07\n"
        ".byte 0x4a\n"
        ".byte 0x07\n"
        ".byte 0x4c\n"
        ".byte 0x13\n"
        ".byte 0x68\n"
        ".byte 0x1b\n"
        ".byte 0x03\n"
        ".byte 0xfc\n"
        ".byte 0xd4\n"
        ".byte 0x21\n"
        ".byte 0x60\n"
        ".byte 0x10\n"
        ".byte 0xf8\n"
        ".byte 0x01\n"
        ".byte 0x1f\n"
        ".byte 0x00\n"
        ".byte 0x29\n"
        ".byte 0xf7\n"
        ".byte 0xd1\n"
        ".byte 0x5d\n"
        ".byte 0xf8\n"
        ".byte 0x04\n"
        ".byte 0x4b\n"
        ".byte 0x70\n"
        ".byte 0x47\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void clear_sdio_state(void) {
    __asm__ volatile(
        ".byte 0x02\n"
        ".byte 0x48\n"
        ".byte 0x38\n"
        ".byte 0x22\n"
        ".byte 0x00\n"
        ".byte 0x21\n"
        ".byte 0xf2\n"
        ".byte 0xf7\n"
        ".byte 0x99\n"
        ".byte 0xbf\n"
        ".byte 0x00\n"
        ".byte 0xbf\n"
        ".byte 0xac\n"
        ".byte 0x2a\n"
        ".byte 0x18\n"
        ".byte 0x00\n"
        ".byte 0x2d\n"
        ".byte 0xe9\n"
        ".byte 0xf8\n"
        ".byte 0x4f\n"
        ".byte 0x5d\n"
        ".byte 0x4b\n"
        ".byte 0x1b\n"
        ".byte 0x68\n"
        ".byte 0xb3\n"
        ".byte 0xf9\n"
        ".byte 0x00\n"
        ".byte 0x30\n"
        ".byte 0x00\n"
        ".byte 0x2b\n"
        ".byte 0x80\n"
        ".byte 0x46\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void log_pool_alloc_b(void) {
    __asm__ volatile(
        ".byte 0x10\n"
        ".byte 0xb5\n"
        ".byte 0xef\n"
        ".byte 0xf3\n"
        ".byte 0x10\n"
        ".byte 0x83\n"
        ".byte 0xdb\n"
        ".byte 0x07\n"
        ".byte 0x03\n"
        ".byte 0xd4\n"
        ".byte 0x72\n"
        ".byte 0xb6\n"
        ".byte 0x0c\n"
        ".byte 0x4b\n"
        ".byte 0x01\n"
        ".byte 0x22\n"
        ".byte 0x1a\n"
        ".byte 0x60\n"
        ".byte 0x0c\n"
        ".byte 0x4c\n"
        ".byte 0x0c\n"
        ".byte 0x48\n"
        ".byte 0x23\n"
        ".byte 0x68\n"
        ".byte 0x01\n"
        ".byte 0x33\n"
        ".byte 0x23\n"
        ".byte 0x60\n"
        ".byte 0x1c\n"
        ".byte 0xf0\n"
        ".byte 0x68\n"
        ".byte 0xff\n"
        ".byte 0x18\n"
        ".byte 0xb1\n"
        ".byte 0x0a\n"
        ".byte 0x4a\n"
        ".byte 0x13\n"
        ".byte 0x68\n"
        ".byte 0x01\n"
        ".byte 0x3b\n"
        ".byte 0x13\n"
        ".byte 0x60\n"
        ".byte 0x23\n"
        ".byte 0x68\n"
        ".byte 0x33\n"
        ".byte 0xb1\n"
        ".byte 0x04\n"
        ".byte 0x4a\n"
        ".byte 0x01\n"
        ".byte 0x3b\n"
        ".byte 0x12\n"
        ".byte 0x68\n"
        ".byte 0x23\n"
        ".byte 0x60\n"
        ".byte 0x0b\n"
        ".byte 0xb9\n"
        ".byte 0x02\n"
        ".byte 0xb1\n"
        ".byte 0x62\n"
        ".byte 0xb6\n"
        ".byte 0x10\n"
        ".byte 0xbd\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void log_tick(void) {
    __asm__ volatile(
        ".byte 0x70\n"
        ".byte 0xb5\n"
        ".byte 0x20\n"
        ".byte 0x4d\n"
        ".byte 0x2b\n"
        ".byte 0x68\n"
        ".byte 0xb3\n"
        ".byte 0xf9\n"
        ".byte 0x00\n"
        ".byte 0x30\n"
        ".byte 0x00\n"
        ".byte 0x2b\n"
        ".byte 0x4f\n"
        ".byte 0xea\n"
        ".byte 0x10\n"
        ".byte 0x26\n"
        ".byte 0xc4\n"
        ".byte 0xb2\n"
        ".byte 0x06\n"
        ".byte 0xdb\n"
        ".byte 0x1c\n"
        ".byte 0x4d\n"
        ".byte 0x24\n"
        ".byte 0x01\n"
        ".byte 0x25\n"
        ".byte 0x44\n"
        ".byte 0xab\n"
        ".byte 0x68\n"
        ".byte 0x33\n"
        ".byte 0xf8\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void rx_queue_head_init(void) {
    __asm__ volatile(
        ".byte 0x0f\n"
        ".byte 0x48\n"
        ".byte 0x30\n"
        ".byte 0xb4\n"
        ".byte 0x20\n"
        ".byte 0xf0\n"
        ".byte 0x03\n"
        ".byte 0x00\n"
        ".byte 0xef\n"
        ".byte 0xf3\n"
        ".byte 0x10\n"
        ".byte 0x83\n"
        ".byte 0xdb\n"
        ".byte 0x07\n"
        ".byte 0x03\n"
        ".byte 0xd4\n"
        ".byte 0x72\n"
        ".byte 0xb6\n"
        ".byte 0x0c\n"
        ".byte 0x4b\n"
        ".byte 0x01\n"
        ".byte 0x22\n"
        ".byte 0x1a\n"
        ".byte 0x60\n"
        ".byte 0x0b\n"
        ".byte 0x4a\n"
        ".byte 0x0c\n"
        ".byte 0x4b\n"
        ".byte 0x11\n"
        ".byte 0x68\n"
        ".byte 0x23\n"
        ".byte 0xf0\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void log_system_init(void) {
    __asm__ volatile(
        ".byte 0x16\n"
        ".byte 0x4b\n"
        ".byte 0x70\n"
        ".byte 0xb5\n"
        ".byte 0x16\n"
        ".byte 0x4e\n"
        ".byte 0x1a\n"
        ".byte 0x68\n"
        ".byte 0x75\n"
        ".byte 0x79\n"
        ".byte 0x96\n"
        ".byte 0xf9\n"
        ".byte 0x07\n"
        ".byte 0x40\n"
        ".byte 0x02\n"
        ".byte 0xf0\n"
        ".byte 0x03\n"
        ".byte 0x02\n"
        ".byte 0x15\n"
        ".byte 0x44\n"
        ".byte 0x6d\n"
        ".byte 0xb2\n"
        ".byte 0x6f\n"
        ".byte 0xf0\n"
        ".byte 0x3d\n"
        ".byte 0x03\n"
        ".byte 0x64\n"
        ".byte 0x1b\n"
        ".byte 0x9c\n"
        ".byte 0x42\n"
        ".byte 0xb8\n"
        ".byte 0xbf\n"
        ".byte 0x1c\n"
        ".byte 0x46\n"
        ".byte 0x64\n"
        ".byte 0xb2\n"
        ".byte 0x20\n"
        ".byte 0x46\n"
        ".byte 0xf3\n"
        ".byte 0xf7\n"
        ".byte 0x27\n"
        ".byte 0xfd\n"
        ".byte 0x21\n"
        ".byte 0x46\n"
        ".byte 0x0d\n"
        ".byte 0x48\n"
        ".byte 0xf4\n"
        ".byte 0x71\n"
        ".byte 0x2a\n"
        ".byte 0x46\n"
        ".byte 0x1f\n"
        ".byte 0xf0\n"
        ".byte 0x5d\n"
        ".byte 0xfc\n"
        ".byte 0x3d\n"
        ".byte 0x34\n"
        ".byte 0x02\n"
        ".byte 0xda\n"
        ".byte 0x00\n"
        ".byte 0x23\n"
        ".byte 0xf3\n"
        ".byte 0x72\n"
        ".byte 0x70\n"
        ".byte 0xbd\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void log_free_pool_e(void) {
    __asm__ volatile(
        ".byte 0x38\n"
        ".byte 0xb5\n"
        ".byte 0x01\n"
        ".byte 0x46\n"
        ".byte 0xef\n"
        ".byte 0xf3\n"
        ".byte 0x10\n"
        ".byte 0x83\n"
        ".byte 0xdb\n"
        ".byte 0x07\n"
        ".byte 0x03\n"
        ".byte 0xd4\n"
        ".byte 0x72\n"
        ".byte 0xb6\n"
        ".byte 0x0e\n"
        ".byte 0x4b\n"
        ".byte 0x01\n"
        ".byte 0x22\n"
        ".byte 0x1a\n"
        ".byte 0x60\n"
        ".byte 0x0d\n"
        ".byte 0x4d\n"
        ".byte 0x0e\n"
        ".byte 0x4c\n"
        ".byte 0x2b\n"
        ".byte 0x68\n"
        ".byte 0x01\n"
        ".byte 0x33\n"
        ".byte 0x2b\n"
        ".byte 0x60\n"
        ".byte 0x23\n"
        ".byte 0x68\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void log_free_pool_f(void) {
    __asm__ volatile(
        ".byte 0x10\n"
        ".byte 0xb5\n"
        ".byte 0x01\n"
        ".byte 0x46\n"
        ".byte 0xef\n"
        ".byte 0xf3\n"
        ".byte 0x10\n"
        ".byte 0x83\n"
        ".byte 0xdb\n"
        ".byte 0x07\n"
        ".byte 0x03\n"
        ".byte 0xd4\n"
        ".byte 0x72\n"
        ".byte 0xb6\n"
        ".byte 0x23\n"
        ".byte 0x4b\n"
        ".byte 0x01\n"
        ".byte 0x22\n"
        ".byte 0x1a\n"
        ".byte 0x60\n"
        ".byte 0x22\n"
        ".byte 0x4c\n"
        ".byte 0x23\n"
        ".byte 0x48\n"
        ".byte 0x23\n"
        ".byte 0x68\n"
        ".byte 0x01\n"
        ".byte 0x33\n"
        ".byte 0x23\n"
        ".byte 0x60\n"
        ".byte 0x19\n"
        ".byte 0xf0\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void fp_convert_uint(void) {
    __asm__ volatile(
        ".byte 0x08\n"
        ".byte 0xb5\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0x5f\n"
        ".byte 0xff\n"
        ".byte 0x15\n"
        ".byte 0xf0\n"
        ".byte 0x87\n"
        ".byte 0xf9\n"
        ".byte 0x05\n"
        ".byte 0xa3\n"
        ".byte 0xd3\n"
        ".byte 0xe9\n"
        ".byte 0x00\n"
        ".byte 0x23\n"
        ".byte 0x15\n"
        ".byte 0xf0\n"
        ".byte 0xda\n"
        ".byte 0xf9\n"
        ".byte 0x15\n"
        ".byte 0xf0\n"
        ".byte 0xba\n"
        ".byte 0xfc\n"
        ".byte 0x08\n"
        ".byte 0xbd\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void fw_config_copy(void) {
    __asm__ volatile(
        ".byte 0x08\n"
        ".byte 0xb5\n"
        ".byte 0x05\n"
        ".byte 0x48\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xc8\n"
        ".byte 0xfc\n"
        ".byte 0x01\n"
        ".byte 0x21\n"
        ".byte 0x40\n"
        ".byte 0xf2\n"
        ".byte 0x2c\n"
        ".byte 0x40\n"
        ".byte 0xfd\n"
        ".byte 0xf7\n"
        ".byte 0x1d\n"
        ".byte 0xfb\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xe1\n"
        ".byte 0xff\n"
        ".byte 0x00\n"
        ".byte 0xbf\n"
        ".byte 0x5c\n"
        ".byte 0xad\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
        ".byte 0x38\n"
        ".byte 0xb5\n"
        ".byte 0x0d\n"
        ".byte 0x46\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void msg_parse(void) {
    __asm__ volatile(
        ".byte 0x0f\n"
        ".byte 0xb4\n"
        ".byte 0x2d\n"
        ".byte 0xe9\n"
        ".byte 0xf0\n"
        ".byte 0x47\n"
        ".byte 0x1e\n"
        ".byte 0x4e\n"
        ".byte 0x73\n"
        ".byte 0x68\n"
        ".byte 0x82\n"
        ".byte 0xb0\n"
        ".byte 0xe3\n"
        ".byte 0xb1\n"
        ".byte 0x0a\n"
        ".byte 0x9c\n"
        ".byte 0xdf\n"
        ".byte 0xf8\n"
        ".byte 0x70\n"
        ".byte 0x80\n"
        ".byte 0xdf\n"
        ".byte 0xf8\n"
        ".byte 0x70\n"
        ".byte 0xa0\n"
        ".byte 0xdf\n"
        ".byte 0xf8\n"
        ".byte 0x70\n"
        ".byte 0x90\n"
        ".byte 0xa7\n"
        ".byte 0x1c\n"
        ".byte 0x20\n"
        ".byte 0x46\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void rf_timer_abort2(void) {
    __asm__ volatile(
        ".byte 0x08\n"
        ".byte 0xb5\n"
        ".byte 0x05\n"
        ".byte 0x48\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xd6\n"
        ".byte 0xfc\n"
        ".byte 0x01\n"
        ".byte 0x21\n"
        ".byte 0x40\n"
        ".byte 0xf2\n"
        ".byte 0x2d\n"
        ".byte 0x40\n"
        ".byte 0xfd\n"
        ".byte 0xf7\n"
        ".byte 0x2b\n"
        ".byte 0xfb\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xef\n"
        ".byte 0xff\n"
        ".byte 0x00\n"
        ".byte 0xbf\n"
        ".byte 0x44\n"
        ".byte 0xad\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
        ".byte 0x08\n"
        ".byte 0xb5\n"
        ".byte 0x05\n"
        ".byte 0x48\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void rf_timer_abort1(void) {
    __asm__ volatile(
        ".byte 0x08\n"
        ".byte 0xb5\n"
        ".byte 0x05\n"
        ".byte 0x48\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xd6\n"
        ".byte 0xfc\n"
        ".byte 0x01\n"
        ".byte 0x21\n"
        ".byte 0x40\n"
        ".byte 0xf2\n"
        ".byte 0x2d\n"
        ".byte 0x40\n"
        ".byte 0xfd\n"
        ".byte 0xf7\n"
        ".byte 0x2b\n"
        ".byte 0xfb\n"
        ".byte 0xff\n"
        ".byte 0xf7\n"
        ".byte 0xef\n"
        ".byte 0xff\n"
        ".byte 0x00\n"
        ".byte 0xbf\n"
        ".byte 0x44\n"
        ".byte 0xad\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
        ".byte 0x08\n"
        ".byte 0xb5\n"
        ".byte 0x05\n"
        ".byte 0x48\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void mm_set_resume_restore_req(void) {
    __asm__ volatile(
        ".byte 0x6d\n"
        ".byte 0x6d\n"
        ".byte 0x5f\n"
        ".byte 0x73\n"
        ".byte 0x65\n"
        ".byte 0x74\n"
        ".byte 0x5f\n"
        ".byte 0x72\n"
        ".byte 0x65\n"
        ".byte 0x73\n"
        ".byte 0x75\n"
        ".byte 0x6d\n"
        ".byte 0x65\n"
        ".byte 0x5f\n"
        ".byte 0x72\n"
        ".byte 0x65\n"
        ".byte 0x73\n"
        ".byte 0x74\n"
        ".byte 0x6f\n"
        ".byte 0x72\n"
        ".byte 0x65\n"
        ".byte 0x5f\n"
        ".byte 0x72\n"
        ".byte 0x65\n"
        ".byte 0x71\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
        ".byte 0x54\n"
        ".byte 0x8f\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void scan_cancel_req_handler(void) {
    __asm__ volatile(
        ".byte 0x73\n"
        ".byte 0x63\n"
        ".byte 0x61\n"
        ".byte 0x6e\n"
        ".byte 0x5f\n"
        ".byte 0x63\n"
        ".byte 0x61\n"
        ".byte 0x6e\n"
        ".byte 0x63\n"
        ".byte 0x65\n"
        ".byte 0x6c\n"
        ".byte 0x5f\n"
        ".byte 0x72\n"
        ".byte 0x65\n"
        ".byte 0x71\n"
        ".byte 0x5f\n"
        ".byte 0x68\n"
        ".byte 0x61\n"
        ".byte 0x6e\n"
        ".byte 0x64\n"
        ".byte 0x6c\n"
        ".byte 0x65\n"
        ".byte 0x72\n"
        ".byte 0x00\n"
        ".byte 0xbc\n"
        ".byte 0x99\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
        ".byte 0x04\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void ke_timer_clear(void) {
    __asm__ volatile(
        ".byte 0x6b\n"
        ".byte 0x65\n"
        ".byte 0x5f\n"
        ".byte 0x74\n"
        ".byte 0x69\n"
        ".byte 0x6d\n"
        ".byte 0x65\n"
        ".byte 0x72\n"
        ".byte 0x5f\n"
        ".byte 0x63\n"
        ".byte 0x6c\n"
        ".byte 0x65\n"
        ".byte 0x61\n"
        ".byte 0x72\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
        ".byte 0x6d\n"
        ".byte 0x73\n"
        ".byte 0x67\n"
        ".byte 0x20\n"
        ".byte 0x21\n"
        ".byte 0x3d\n"
        ".byte 0x20\n"
        ".byte 0x4e\n"
        ".byte 0x55\n"
        ".byte 0x4c\n"
        ".byte 0x4c\n"
        ".byte 0x00\n"
        ".byte 0x9d\n"
        ".byte 0x80\n"
        ".byte 0x44\n"
        ".byte 0x69\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void hal_dma_evt(void) {
    __asm__ volatile(
        ".byte 0x68\n"
        ".byte 0x61\n"
        ".byte 0x6c\n"
        ".byte 0x5f\n"
        ".byte 0x64\n"
        ".byte 0x6d\n"
        ".byte 0x61\n"
        ".byte 0x5f\n"
        ".byte 0x65\n"
        ".byte 0x76\n"
        ".byte 0x74\n"
        ".byte 0x00\n"
        ".byte 0x09\n"
        ".byte 0x0b\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
        ".byte 0x74\n"
        ".byte 0x70\n"
        ".byte 0x63\n"
        ".byte 0x5f\n"
        ".byte 0x75\n"
        ".byte 0x70\n"
        ".byte 0x64\n"
        ".byte 0x61\n"
        ".byte 0x74\n"
        ".byte 0x65\n"
        ".byte 0x5f\n"
        ".byte 0x66\n"
        ".byte 0x72\n"
        ".byte 0x61\n"
        ".byte 0x6d\n"
        ".byte 0x65\n"
    );
}

__attribute__((naked, used, section(".text.v18")))
void apm_stop_cac_req_handler(void) {
    __asm__ volatile(
        ".byte 0x61\n"
        ".byte 0x70\n"
        ".byte 0x6d\n"
        ".byte 0x5f\n"
        ".byte 0x73\n"
        ".byte 0x74\n"
        ".byte 0x6f\n"
        ".byte 0x70\n"
        ".byte 0x5f\n"
        ".byte 0x63\n"
        ".byte 0x61\n"
        ".byte 0x63\n"
        ".byte 0x5f\n"
        ".byte 0x72\n"
        ".byte 0x65\n"
        ".byte 0x71\n"
        ".byte 0x5f\n"
        ".byte 0x68\n"
        ".byte 0x61\n"
        ".byte 0x6e\n"
        ".byte 0x64\n"
        ".byte 0x6c\n"
        ".byte 0x65\n"
        ".byte 0x72\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
        ".byte 0x00\n"
        ".byte 0x1c\n"
        ".byte 0xc3\n"
        ".byte 0x16\n"
        ".byte 0x00\n"
    );
}
